### ISSUE TITLE
Is there a way to control precision of the generated background positions?

### ISSUE THREAD

**Issue by muffinresearch** [jkphl/svg-sprite#102]
Using grunt-svg-sprite I noticed I'm getting values like:

```css
.sprite-icon {
     background-position: 0 66.29270780214176%;
     width: 40px;
     height: 25.12px;
}
```
I'd like to turn down the precision on the background-position percentages if possible.

Is there any setting to affect that? FWIW I see `shape.dimension.precision` only affects the height/width values.
