### ISSUE TITLE
How change the id based in path?

### ISSUE THREAD

**Issue by marcosalberto** [jkphl/svg-sprite#174]
I have icons in different directories, then is possible a ID conflict. To fix i need put the component name in the icon id, example below.

Example:
An icon on **/component-a/icons/search.svg** should have the ID **icon-component-a--search**

I tried to use the shape.generator.id option with function, but it signature only have the icon name.

Is there any solution?

Thank you

**Comment by marcosalberto** [comment]
A way to solve without side effects was add the Vynil of icon to the shape.generator.id function, don't know if is a good solution. But can help others.

**Comment by jkphl** [comment]
@marcosalberto Adding the vinyl source shouldn't be necessary as the default generator function already takes directory names into account (if configured correctly). Please read the [docs about the default generator function](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#shape-ids), it states that the

> directory structures get traversed using the `id.separator` as replacement for the directory separator.

It all depends on the base directory from which you match your SVG shapes. I usually use something like this:

```
var cwd = '/path/to/svg/base';
require('glob').glob('**/*.svg', {cwd: cwd}, function(err, files) {
        files.forEach(function(file){
                spriter.add(
                        path.resolve(path.join(cwd, file)),
                        file,
                        fs.readFileSync(path.join(cwd, file), {encoding: 'utf-8'})
                );
        });
}
```

Inside the loop `file` should contain the relative directory structure, e.g. `path/below/base-dir.svg`,  which will get passed to the generator function. So adding the vinyl source seems redundant to me. Do you agree?

**Comment by marcosalberto** [comment]
Thank you for the answer, this is exactly what i need but doesn't work. Or i'm doing something wrong.

I created the issue in the wrong place, i'm using Gulp and my task is like below. Already tried with absolute path and relative path.

```
var iconsLis = [ 
  "typo3conf/components/header/icons/icon-search.svg",
  "typo3conf/components/search_result/icons/icon-search.svg"
];

var rootPath = path.resolve(__dirname)

gulp.task("icons", function() {

    return gulp.src(iconsList, { cwd: rootPath })
    .pipe(svgSprite({
      mode: {
        symbol: {
          dest: ".",
          sprite: "icons.svg"
        }
      }
    }))
    .pipe(gulp.dest("./fileadmin/icons"))
});
```

**Comment by marcosalberto** [comment]
@jkphl,

I have multiples directories and because of that doesn't work.

**Comment by jkphl** [comment]
It must be a problem with your spriter config or the way you pass in the source SVGs.

Given a source structure like this:

```
assets/
|-- a
|   |-- weather-clear.svg
|   `-- weather-overcast.svg
`-- b
    |-- weather-snow.svg
    `-- weather-wind.svg
```

and a spriter config / script like this:

```js
var gulp = require('gulp'),
    svgSprite = require('gulp-svg-sprite'),
    path = require('path'),
    config = {
        log: 'verbose',
        shape: {
            id: {
                generator: function(name) {
                    console.log('Input parameter (name)', name);
                    return path.basename(name.split(path.sep).join(this.separator).replace(/\s+/g, this.whitespace), '.svg');
                }
            }
        },
        mode: {
            css: {
                dest: '',
                sprite: 'sprite.svg',
                bust: false,
                render: {
                    css: true
                }
            }
        }
    };

gulp.task('default', function () {
    return gulp.src('**/*.svg', {cwd: 'assets'})
        .pipe(svgSprite(config))
        .pipe(gulp.dest('icons'));
});
```

I get perfect results:

```css
.svg-a--weather-clear {
	background: url("sprite-dc98f4c6.svg") 0 0 no-repeat;
}

.svg-a--weather-clear-dims {
	width: 48px;
	height: 48px;
}

.svg-a--weather-overcast {
	background: url("sprite-dc98f4c6.svg") 100% 0 no-repeat;
}

.svg-a--weather-overcast-dims {
	width: 48px;
	height: 48px;
}

.svg-b--weather-snow {
	background: url("sprite-dc98f4c6.svg") 0 100% no-repeat;
}

.svg-b--weather-snow-dims {
	width: 48px;
	height: 48px;
}

.svg-b--weather-wind {
	background: url("sprite-dc98f4c6.svg") 100% 100% no-repeat;
}

.svg-b--weather-wind-dims {
	width: 48px;
	height: 48px;
}
```

The log output is:

```
[02:51:25] Using gulpfile /www/vhtdocs/lab/gulp-playground/gulpfile.js
[02:51:25] Starting 'default'...
2016-06-19 02:51:25 - verbose: Initialized spriter configuration
2016-06-19 02:51:25 - info: Created spriter instance
Input parameter (name) a/weather-clear.svg
2016-06-19 02:51:25 - verbose: Added shape "a--weather-clear:regular"
Input parameter (name) a/weather-overcast.svg
2016-06-19 02:51:26 - verbose: Added shape "a--weather-overcast:regular"
Input parameter (name) b/weather-snow.svg
2016-06-19 02:51:26 - verbose: Added shape "b--weather-snow:regular"
Input parameter (name) b/weather-wind.svg
2016-06-19 02:51:27 - verbose: Added shape "b--weather-wind:regular"
2016-06-19 02:51:27 - info: Compiling 4 shapes ...
2016-06-19 02:51:27 - info: Laying out «css» sprite («css» mode)
2016-06-19 02:51:27 - verbose: Created «css» SVG sprite file («css» mode)
2016-06-19 02:51:27 - verbose: Created «css» stylesheet resource
2016-06-19 02:51:27 - info: Finished «css» sprite compilation
2016-06-19 02:51:27 - info: Created 1 x SVG, 1 x CSS
2016-06-19 02:51:27 - verbose: Created sprite.css: 550 Bytes
2016-06-19 02:51:27 - verbose: Created sprite.svg: 45.3 kB
[02:51:27] Finished 'default' after 2.24 s
```

Please double-check your config and the name parameter passed into the generator function. Be aware that the default separator for replacing directory borders is `"--"`.
