### ISSUE TITLE
'background: url()' support full url path ?

### ISSUE THREAD

**Issue by linrz** [jkphl/svg-sprite#268]
I packaged the SVG as a sprite in the project and uploaded it to the CDN, so I hope the background URL is the complete CDN path.When I use it, I find that there is a problem with the generated path. The protocol header is missing '/'
```js
spriter.compile({
  css: {
    sprite: 'test.svg',
    layout: 'vertical',
    dimensions: true,
    bust: false,
    sprite: 'https://xxx.cdn/svg/menu',
    render: {
      scss: true
    }
  }
}, (err, result) => {
  
});
```
The result is the following code.
```css
%svg-common {
    background: url("https:/xxx.cnd/svg/menu/test.svg") no-repeat;
}
```
Is there a problem with my configuration ? Thank you for your reply.
