### ISSUE TITLE
Make "cssmin" optional for style blocks

### ISSUE THREAD

**Issue by Smidds** [jkphl/svg-sprite#365]
### Some Context
When specifying animation keyframes to the `style` block, `cssmin` appears to destroy the definition of those animations!

**Example SVG**
```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 155 172">
    <defs>
        <style>
            @keyframes spin {
                0% {
                    transform:rotate(0deg);
                } 

                100% { 
                    transform:rotate(180deg);
                }
            }

            @keyframes dashHide { 
                0% {
                    clip-path: circle(35% at 50% 60%);
                } 

                100% {
                    clip-path: circle(75%);
                }
            }            
        </style>
    </defs>
</svg>
```

**Resulting `style` block after `cssmin`ification**
```css
'@keyframes spin{0%{transform:rotate(0deg)}to{transform:rotat{transform:rotate(180deg)}}@keyframes dashHide{0%{clip-path:circle(35%}@keyframes dashHide{0%{clip-path:circle(35% at 50% 60%)}to{clip-path:circle(75%)}}{clip-path:circle(75%)}}}'
```
It should, in this single-line form, look like this:
```css
@keyframes spin{0%{transform:rotate(0deg)}to{transform:rotate(180deg)}}@keyframes dashHide{0%{clip-path:circle(35% at 50% 60%)}to{clip-path:circle(75%)}}
```

### My Modest Proposla
Make the usage of `cssmin` optional! It seems `svgo` does a pretty good job cleaning up all my whitespace in this style block, and I'd like to remove this functionality seeing as I personally have no use for it and would like to preserve these animations.

I'm happy to make a pull-request adding an option passed via the config to disable, if that would be welcome!
