### ISSUE TITLE
Custom variable callback doesn't work correctly

### ISSUE THREAD

**Issue by thasmo** [jkphl/svg-sprite#50]
I'm trying to use a similar variable definition as defined in the docs, but all it does is print the function as string into the template, which looks like this:
```scss
%svg-common {
	background-repeat: no-repeat;
	background-image: url(function (sprite, render) {
					return render(sprite).split('.svg').join('.png');
				});

	.svg & {
		background-image: url(../image/sprite.svg);
	}
}
```
My configuration looks like this:
```js
{
	variables: {
		png: function() {
			return function(sprite, render) {
				return render(sprite).split('.svg').join('.png');
			}
		}
	}
}
```
My template is this:
```scss
{{#common}}.{{/common}}{{^common}}%{{/common}}{{mixin}} {
	background-repeat: no-repeat;
	background-image: url({{{png}}});

	.svg & {
		background-image: url({{{sprite}}});
	}
}
```

Haven't found anything why mustache shouldn't run the function and instead print it. Any idea?
