### ISSUE TITLE
Responsive SVG sprites

### ISSUE THREAD

**Issue by alexanderby** [jkphl/svg-sprite#80]
There is a problem when trying to scale an SVG icon that is included into an SVG sprite in different browsers: *zoom* property only works in Chrome and pixelates images in IE; *transform* property works in FireFox and Chrome but causes layout mispositioning and either pixelates images in IE.

### For being able to scale SVG sprite items the next things can be done:
- Output sprite size in EMs. Then it would be possible to scale an element, which contains an icon, using *font-size* property.
``` css
.icon {
    background: url(sprite.svg) 25% 25%;
    width: 1em;
    height: 1em;
    background-size: 8em 4em;
}
```
``` html
<span class="icon" style="font-size: 2em; font-size: 200%;"></span>
```
- Output background sizes for different scale ratios (less preferred).
``` css
.icon {
    background: url(sprite.svg) 25% 25%;
}
.scale_1 {
    background-size: 128px 64px;
}
.scale_2 {
    background-size: 256px 128px;
}
```
``` html
<span class="icon scale_2"></span>
```

See the example: http://jsfiddle.net/alexanderby/yvcdcm80/
